### ISSUE TITLE
All posts timeline is very slow to display

### ISSUE THREAD

**Issue by taldcroft** [astropy/astropython.org#15]
It takes about 15 seconds to load, whereas this particular page would often just be to quickly check what's new.  Presumably this is related to the generation of corresponding tags?  Maybe there is a way to do caching or something, but otherwise I would suggest removing the tags in favor of snappy performance for this page.

**Comment by amanjhunjhunwala** [comment]
Have added a new mechanism for timeline...after going to the timeline, there is an option to switch to advanced view with all the filtering etc ! 
This  makes the page 10 seconds faster on GT Testing ! 
Reopen this issue of you're not happy with it @taldcroft

**Comment by amanjhunjhunwala** [comment]
Need to make it faster ! Looking on possible solutions...

**Comment by pllim** [comment]
The whole website feels slow to me.

**Comment by amanjhunjhunwala** [comment]
Hi ! 
We do realize that occasionally the site gets slow. We use only 2 mini  web workers in our application, hence every time 2 or more concurrent users actively use the site, all of them experience a somewhat lesser speed.  

The site performance metrics can be found at https://github.com/x-calibre/astropython/issues/90 . The original dev copy of this repo. The site is now twice as fast as it was before when only 1 user is there.

I guess much of this has to do with the fact that we use a completely maintenance free app hosting platform , which means less maintenance(obviously) but at the cost of lack of underlying customizability (we cannot schedule the web workers according to our algorithms, use custom load balancing, etc.) Plus PythonAnywhere (the hosting platform) uses only MySQL databases , which are slower compared to modern NoSQL/Postgres Databases.It is going to add support for Postgres soon and hopefully then, the site should be faster.

We do not use CDN hosting as well, but use compressed static assets , which do increase the speed but not as much as a CDN.

If required, we could shift to AWS but that would significantly increase the backend maintenance which is 0 currently.
