### ISSUE TITLE
Educational resources: course contents not formatted

### ISSUE THREAD

**Issue by taldcroft** [astropy/astropython.org#16]
How do I put in a bulleted list of items for course contents?  See:
http://www.astropython.org/education/practical-python-for-astronomers-aka-python4astron/

**Comment by amanjhunjhunwala** [comment]
The newline error has been fixed , Sorry that it just skipped all the checks !

**Comment by amanjhunjhunwala** [comment]
@taldcroft  Now headers of optional fields that are blank will not be displayed as well  , Hope this resolves the issue ...
