### ISSUE TITLE
Better rating display

### ISSUE THREAD

**Issue by cdeil** [astropy/astropython.org#18]
With the current rating display I can't tell whether I already did rate this:

<img width="218" alt="screen shot 2015-09-10 at 22 09 49" src="https://cloud.githubusercontent.com/assets/852409/9799648/deeba91c-5808-11e5-979a-ded1ba4ed768.png">

So a few times I accidentally clicked the thumbs up symbol and thus deleted my thumbs up vote for this item, because I didn't remember I had clicked it at some point in the past.

Can you please display this info on whether I already rated and make this simpler to use?

**Comment by amanjhunjhunwala** [comment]
Definately ! Working on it !
