### ISSUE TITLE
astroplan package is half-present on the site

### ISSUE THREAD

**Issue by cdeil** [astropy/astropython.org#19]
Yesterday I added astroplan.
It's now found via search:
http://www.astropython.org/search?section=all&q=astroplan

![screen shot 2015-09-11 at 10 27 18](https://cloud.githubusercontent.com/assets/852409/9810309/f579b752-586f-11e5-831e-b4e3ef0a91e7.png)

But when I click on "view more", I get a 500 "not found" error:
http://www.astropython.org/packages/astroplan/

![screen shot 2015-09-11 at 10 27 33](https://cloud.githubusercontent.com/assets/852409/9810313/f9ba5894-586f-11e5-849e-1d8560d695b9.png)

So it seems astroplan is half-present in the list of packages?

**Comment by amanjhunjhunwala** [comment]
It was waiting for moderator approval , it is currently being displayed  at http://www.astropython.org/packages/astroplan/

**Comment by cdeil** [comment]
But then while it was waiting for moderator approval, I guess it also shouldn't have been listed in the search results, no?

**Comment by amanjhunjhunwala** [comment]
It will be rectified soon ! Working on it !

**Comment by taldcroft** [comment]
astroplan appears to be there as desired now.
