### ISSUE TITLE
Make tags click-able in the package list

### ISSUE THREAD

**Issue by bsipocz** [astropy/astropython.org#20]
I think it would be a quite comfortable feature to make the tags click-able from the package list. Right now they are listed with black, and one has to go down on the page and look for the given tag on the right side from all the tags to make a filtering.

![screen shot 2015-09-11 at 12 10 38](https://cloud.githubusercontent.com/assets/6788290/9813533/369472aa-587e-11e5-8dca-2a00b6a5a97d.png)

**Comment by amanjhunjhunwala** [comment]
Done ! www.astropython.org/packages

@taldcroft @bsipocz  Should I close this?

**Comment by bsipocz** [comment]
Wow, this was quick. thanks
