### ISSUE TITLE
Not getting moderation requests

### ISSUE THREAD

**Issue by taldcroft** [astropy/astropython.org#22]
I don't seem to be getting moderation requests.  I took a tour through the admin interface and couldn't find a way to set this.

**Comment by amanjhunjhunwala** [comment]
@taldcroft Sorry , there was a spelling error in the email id....
It has been rectified. I just posted a test post, do tell me if you received the mail !

**Comment by taldcroft** [comment]
OK, I got the email (thanks!), but the link in the email is not ideal since it sends me to the not-yet-available post: http://www.astropython.org/blog/sample-test-blog/.  Seems like it should go to the admin interface entry.

**Comment by amanjhunjhunwala** [comment]
Done !
It takes you to the moderation panel (as of now) !

When I implement the new moderation technique in about 2 weeks , you will be able to approve the post from your mail ! 

Should I close this and #20 now?

**Comment by taldcroft** [comment]
Yup, both issues look resolved.
