### ISSUE TITLE
No email notifications

### ISSUE THREAD

**Issue by pllim** [astropy/astropython.org#24]
I never get any notifications whether my edits or new posts are accepted (and published) or rejected.

**Comment by amanjhunjhunwala** [comment]
Thanks for the query ! 
That happens only in the case where users log in via Github tell Github was told by the user not to share their email ids with anyone (in your Github account settings). Therefore we get a unique token for the user to identify his Github account but not his email.
We could add in an addition to the website where we ask the email id for such users explicitly the next time they log in.

**Comment by pllim** [comment]
Ah, okay. Yes, I used GitHub. IMHO the behavior should be consistent across the board. It does not make sense for user to get notified if they sign in via _this_ or _this_ but not _that_.
