### ISSUE TITLE
Need alphabetical shortcut on top of package listing

### ISSUE THREAD

**Issue by pllim** [astropy/astropython.org#26]
If I want to see a package that starts with, say, V, I have to scroll all the way down. Would be nice if I can just click "V" on top and it jumps to V section.

Alternatively, it can also have a top section listing all the package names in small fonts, and clicking on it jumps to the package.

But the first option is probably cleaner.

**Comment by amanjhunjhunwala** [comment]
Thank you so much for the suggestion. Will try to add it by next week !
