### ISSUE TITLE
What does "recommended" package really mean?

### ISSUE THREAD

**Issue by pllim** [astropy/astropython.org#27]
Would anyone who upload their own package say that it is _not_ recommended?

**Comment by pllim** [comment]
Maybe a more useful tag is "stable".

**Comment by amanjhunjhunwala** [comment]
Hi , Thank you so much for the query.
This was something that was initially suggested by @taldcroft and team. I guess the "Recommended" packages signified those packages which were recommended for use and were regularly maintained. I could easily change the name if required.

**Comment by pllim** [comment]
This explanation should be documented in a user-facing way when they add/edit a package. One way could be a tooltip when user hover over that category, but I wonder if that would be obvious enough.
