### ISSUE TITLE
How to add new package tags?

### ISSUE THREAD

**Issue by pllim** [astropy/astropython.org#28]
How do add a new package tag?

**Comment by amanjhunjhunwala** [comment]
New package tags are automatically generated when a user creates a new package or when he edits the tags for an old one. If the tag is not already present in the list shown, add it in a comma sepearted list in words and it is automatically added
![image](https://cloud.githubusercontent.com/assets/10886527/14059911/33323288-f378-11e5-9494-49c2bd9e5ccd.png)

**Comment by amanjhunjhunwala** [comment]
Editing old package tags takes place by clicking the pencil icon next to "Tags" and adding in the tag 
![image](https://cloud.githubusercontent.com/assets/10886527/14059940/1da046ca-f379-11e5-8907-181fa1acad7b.png)
![image](https://cloud.githubusercontent.com/assets/10886527/14059947/316bb568-f379-11e5-8c4d-d2d200504348.png)

**Comment by amanjhunjhunwala** [comment]
Should I close this issue ?

**Comment by pllim** [comment]
Not yet.
1. Are the tag names case-sensitive? If user type "fits", will there be _two_ different tags about FITS now, i.e., "fits" and "FITS"? If so, that is undesirable.
2. How to add your own _new_ tags when you add a package should be documented. Having never used the site before, my instinct was to choose from existing tags by clicking on them. It did not occur to me I could add _new_ ones by typing it manually in the text box. A prettier way (and perhaps harder to implement and thus not feasible) is to have a "+ new tag" tag at the end of the existing ones, where user can click to enter a new tag. Or something more obvious like that.
