### ISSUE TITLE
How to add moderators that receive email moderation requests

### ISSUE THREAD

**Issue by taldcroft** [astropy/astropython.org#29]
It looks like the list of moderator email addresses is hardwired.  Could this be made into an attribute of users?  Or some other strategy?  Even just editing the file is OK if that is the right thing.

**Comment by taldcroft** [comment]
Or make any trusted user be effectively a moderator that gets email notifiication?

**Comment by amanjhunjhunwala** [comment]
Hi ! I will try and definitely add it by next week ! Should be easy..... The infrastructure is there , just need to add a query to the Database everytime a new user posts.
