### ISSUE TITLE
Error 500 on home page

### ISSUE THREAD

**Issue by hamogu** [astropy/astropython.org#30]
![screenshot](https://cloud.githubusercontent.com/assets/498688/20566463/2f825678-b163-11e6-900c-4d471b1ad113.png)

This is with Firefox ESR 45.4.0 on 2016-11-23 at 9:55 am EST.

**Comment by jeanconn** [comment]
I'm just getting a 502 on www.astropython.org at this point

![502](https://cloud.githubusercontent.com/assets/791508/20578850/5e6056a0-b197-11e6-9caf-52f32c7cfee9.png)

@x-calibre would you take a look when you get a chance?

**Comment by amanjhunjhunwala** [comment]
@jeanconn Done ! There was some issue with the server. Cleaned it and its back on !

**Comment by amanjhunjhunwala** [comment]
You could check once and reopen the issue if the problem persists !  (Hopefully its not a region thing ! )
