### ISSUE TITLE
login or create account no working

### ISSUE THREAD

**Issue by tbhkuiper** [astropy/astropython.org#32]
Trying to log in to AstroPython via Google or Github throws up an error page.  The home page does not provide an option to create an account.  The login button has no link or action.  The contact page has no link, but maybe that's because I'm not logged in.  In short, all the doors are locked and no one appears to be at home.

**Comment by ajhunjhunwal** [comment]
Seems like the Oauth certificates expired for login. Probably need to look into renewing their APIs
